version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.sample
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ashutosh
      MYSQL_PASSWORD: ashutosh@123
      MYSQL_DATABASE: medicsstore_data
    volumes:
      - medicsstore_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
volumes:
  medicsstore_data: