version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.sample
    depends_on:
      - db
  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medics_store
      MYSQL_USER: ashutosh
      MYSQL_PASSWORD: ashutosh@123
    ports:
      - "3306:3306"
    volumes:
      - medicsstore_data:/var/lib/mysql

volumes:
  medicsstore_data: